### PR TITLE
chore: bump deps

### PR DESCRIPTION
**Pull request by DmitriyMV**
- run rekres
- github.com/Masterminds/sprig/v3 to v3.3.0
- github.com/google/go-github to v65.0.0
- github.com/moby/buildkit to v0.16.0
- golang.org/x/oauth2 to v0.23.0

### CODE REVIEW

**Review by smira — APPROVED** [review]
I don't there's any real need to bump anything here?

**Comment by DmitriyMV** [comment]
@smira rekres brings most of the stuff, including bumps to tools and Go (from 1.22 to 1.23).

**Comment by smira** [comment]
> @smira rekres brings most of the stuff, including bumps to tools and Go (from 1.22 to 1.23).

I understand that, but why? Is there a known issue? Update would make it better in some way? Fix some bug?

**Comment by DmitriyMV** [comment]
> > @smira rekres brings most of the stuff, including bumps to tools and Go (from 1.22 to 1.23).
> 
> I understand that, but why? Is there a known issue? Update would make it better in some way? Fix some bug?

As for using facing changes, no I don't think so. Internally binary will probably work a little bit better, but other than that, no, probably not. 

We can merge this, but do not bump the resulting commit until we get changes that are actually user visible.

**Comment by smira** [comment]
I'm not opposed to this PR in particular, but I might see it being a bit of an effort we could skip, as bumping bldr version across our fleet is also a long way to go. So I'd rather bump as we make actual changes to bldr, so that bumping bldr at least provides are some fixes/changes.

**Comment by smira** [comment]
@DmitriyMV let's merge this?

**Pull request merged**
